param([string]$adminpassword)
choco install mssqlserver2016expressadv --ia "/QUIET /IACCEPTSQLSERVERLICENSETERMS /IACCEPTROPENLICENSETERMS /ACTION=install /ADDCURRENTUSERASSQLADMIN /SAPWD=$adminpassword  /INSTANCEID=SQLEXPRESS /INSTANCENAME=SQLEXPRESS /SECURITYMODE=SQL /SQLBACKUPDIR=`"C:\SqlBackup`" /SQLUSERDBDIR=`"C:\SqlData`" /INSTALLSQLDATADIR=`"C:\SqlData`" /SQLUSERDBLOGDIR=`"C:\SqlLogs`" /SQLCOLLATION=Latin1_General_BIN /UPDATEENABLED=FALSE /FEATURES=SQL" -o -y --no-progress

