#Requires -Version 5.0 -RunAsAdministrator
#This PowerShell script is generated by the AMT Component Deployment Center
param (
  
    [string]$username,
    [string]$password
)

Invoke-Expression "C:\\AMT\\SCRIPTS\\deploy_sql_express_choco.ps1 -adminpassword $password"
     


